[mongodb]
3.91.81.170
#mongodb.srinunayak.online
[catalogue]
catalogue.srinunayak.online
[redis]
redis.srinunayak.online
[user]
user.srinunayak.online
[cart]
cart.srinunayak.online
[mysql]
mysql.srinunayak.online
[shipping]
shipping.srinunayak.online
[rabbitmq]
rabbitmq.srinunayak.online
[payment]
payment.srinunayak.online
[all.vars]
ansible_user=ec2-user
ansible_password=DevOps321