- name: stop the {{ component }}
  ansible.builtin.service:
    name: "{{ component }}"

- name: remove the old version
  ansible.builtin.file:
    name: /app 
    state: absent

- name: download the new {{ component }} code 
  ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-{{ app-version }}.zip
      dest: /tmp/{{ component }}.zip 

- name: unzip the {{ component }}code 
  ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip 
      dest: /app
      remote_src: yes

- name: install dependencies 
  community.general.npm:
      path: /app