
  - name: install maven 
    ansible.builtin.dnf:
      name: maven
      state: installed 
      

  - name: install dependencies
    ansible.builtin.command: mvn clean package  
    args:
      chdir: /app 

  - name: move the target from one place to another place 
    ansible.builtin.command: mv target/{{ component }}-1.0.jar {{ component }}.jar 
    args:
      chdir: /app 
