- name: import app-setup
  include_role:
    name: common
    tasks_from: app-setup

- name: import nodejs-setup
  include_role:
    name: common
    tasks_from: nodejs-setup

- name: import systemd-setup
  include_role:
    name: common
    tasks_from: systemd-setup
